// Generated by tools/release/gen-release-notes.mjs.
import type { PaletteLabel } from '$lib/palette';

export const RELEASE_HUES = ["Purple","Blue","Green","Orange","Pink","Red"] as const satisfies readonly PaletteLabel[];
export type ReleaseHue = (typeof RELEASE_HUES)[number];

export function parseReleaseHue(value: unknown): ReleaseHue {
  for (const hue of RELEASE_HUES) if (value === hue) return hue;
  throw new Error(`Unknown release hue: ${String(value)}`);
}
