export const STORAGE_KEYS = {
  soundEnabled: 'splotch-sound-enabled',
  soundVolume: 'splotch-sound-volume',
  actionButtonScale: 'splotch-action-button-scale',
  saveOnDelete: 'splotch-save-on-delete',
  screenshotEnabled: 'splotch-screenshot-enabled',
  undoButtonEnabled: 'splotch-undo-button-enabled',
  strokeWidthControl: 'splotch-stroke-width-control',
  crayonEnabled: 'splotch-crayon-enabled',
  magicBrushEnabled: 'splotch-magic-brush-enabled',
  eraserEnabled: 'splotch-eraser-enabled',
  coloringBookEnabled: 'splotch-coloring-book-enabled',
  coloringPacksAllowMetered: 'splotch-coloring-packs-allow-metered',
  aiImageEnabled: 'splotch-ai-image-enabled',
  aiCustomizationEnabled: 'splotch-ai-customization-enabled',
  autoSaveAi: 'splotch-auto-save-ai',
  aiAccessToken: 'splotch-ai-access-token',
  advancedControls: 'splotch-advanced-controls',
  drawerOpen: 'splotch-drawer-open',
  lockRotation: 'splotch-lock-rotation',
  forceLandscape: 'splotch-force-landscape',
  pencilEraserEnabled: 'splotch-pencil-eraser-enabled',
  applePencilSeen: 'splotch-apple-pencil-seen',
  theme: 'splotch-theme',
  brushType: 'splotch-brush-type',
  strokeWidthSize: 'splotch-stroke-width-size',
  eraserWidthSize: 'splotch-eraser-width-size',
  installDismissed: 'splotch-install-dismissed',
  installCompleted: 'splotch-install-completed',
  installRepromptSessionCount: 'splotch-install-reprompt-session-count',
  installRepromptsUsed: 'splotch-install-reprompts-used',
  legacyAiUserApiKey: 'splotch-ai-user-api-key',
  saveFolderChosen: 'splotch-save-folder-chosen',
  parentalGateAiImageMode: 'splotch-parental-gate-ai-image-mode',
  parentalGateImageReportMode: 'splotch-parental-gate-image-report-mode',
  parentalGateExternalLinksMode: 'splotch-parental-gate-external-links-mode',
  parentalGateFeedbackMode: 'splotch-parental-gate-feedback-mode',
  parentalGateParentCenterMode: 'splotch-parental-gate-parent-center-mode',
  parentSectionsSeen: 'splotch-parent-sections-seen',
  settingsActivitySessionCount: 'splotch-settings-activity-session-count',
  legacyGateRememberMode: 'splotch-gate-remember-mode',
  legacyGateUnlockedForever: 'splotch-gate-unlocked',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
