export const STORAGE_KEYS = {
  soundEnabled: 'splotch-sound-enabled',
  soundVolume: 'splotch-sound-volume',
  actionButtonScale: 'splotch-action-button-scale',
  saveOnDelete: 'splotch-save-on-delete',
  screenshotEnabled: 'splotch-screenshot-enabled',
  undoButtonEnabled: 'splotch-undo-button-enabled',
  strokeWidthControl: 'splotch-stroke-width-control',
  eraserEnabled: 'splotch-eraser-enabled',
  coloringBookEnabled: 'splotch-coloring-book-enabled',
  aiImageEnabled: 'splotch-ai-image-enabled',
  aiCustomizationEnabled: 'splotch-ai-customization-enabled',
  autoSaveAi: 'splotch-auto-save-ai',
  aiAccessToken: 'splotch-ai-access-token',
  advancedControls: 'splotch-advanced-controls',
  drawerOpen: 'splotch-drawer-open',
  adminLinkVisible: 'splotch-admin-link-visible',
  lockRotation: 'splotch-lock-rotation',
  forceLandscape: 'splotch-force-landscape',
  pencilEraserEnabled: 'splotch-pencil-eraser-enabled',
  applePencilSeen: 'splotch-apple-pencil-seen',
  theme: 'splotch-theme',
  brushType: 'splotch-brush-type',
  strokeWidthSize: 'splotch-stroke-width-size',
  eraserWidthSize: 'splotch-eraser-width-size',
  installDismissed: 'splotch-install-dismissed',
  installCompleted: 'splotch-install-completed',
  legacyAiUserApiKey: 'splotch-ai-user-api-key',
  saveFolderChosen: 'splotch-save-folder-chosen',
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
