<script module lang="ts">
  export const RELEASE_NOTE_SECTION_COUNT = 3;
</script>

<script lang="ts">
  let { visibleSections = RELEASE_NOTE_SECTION_COUNT }: { visibleSections?: number } = $props();
</script>

<!-- Generated by scripts/generate-releases.mjs from releases/1.4.0.md. -->
{#if visibleSections >= 1}
  <h2>✨ New</h2>
  <ul>
    <li>Dark mode — Light, Dark, or follow your device.</li>
    <li>A wax crayon brush, from the new Brush Menu.</li>
    <li>The magic brush now works on any drawing.</li>
    <li>Report a bug from Settings.</li>
  </ul>
{/if}
{#if visibleSections >= 2}
  <h2>🚀 Improved</h2>
  <ul>
    <li>Rotating your device keeps the paper upright.</li>
    <li>Undo now goes back 20 steps.</li>
    <li>A bigger eraser, sized as holes in the paper.</li>
  </ul>
{/if}
{#if visibleSections >= 3}
  <h2>🛠 Fixed</h2>
  <ul>
    <li>The magic brush no longer leaves ghost outlines.</li>
    <li>Swatches and pages read correctly in dark mode.</li>
    <li>The drag-to-clear tutorial no longer vanishes instantly.</li>
  </ul>
{/if}
