<script module lang="ts">
  export const RELEASE_NOTE_SECTION_COUNT = 3;
</script>

<script lang="ts">
  import ReleaseSectionHeading from '$lib/components/ReleaseSectionHeading.svelte';

  let {
    headingLevel,
    visibleSections = RELEASE_NOTE_SECTION_COUNT,
  }: { headingLevel: 4 | 5; visibleSections?: number } = $props();
</script>

<!-- Generated by tools/release/gen-release-notes.mjs from releases/1.6.0.md. -->
{#if visibleSections >= 1}
  <ReleaseSectionHeading title="New" level={headingLevel} />
  <ul>
    <li>Pick sounds for each part of the app — plus a clear sound.</li>
    <li>Dottie the mascot now reacts on error screens.</li>
  </ul>
{/if}
{#if visibleSections >= 2}
  <ReleaseSectionHeading title="Improved" level={headingLevel} />
  <ul>
    <li>AI pictures are opt-in, with clearer errors and retries.</li>
    <li>Playful motion: menus pop from buttons, undo spins, clearing sweeps to the trash.</li>
    <li>Crisper coloring pages that load faster.</li>
    <li>Smoother drawing on iPad and Android.</li>
    <li>App updates apply without interrupting drawing.</li>
  </ul>
{/if}
{#if visibleSections >= 3}
  <ReleaseSectionHeading title="Fixed" level={headingLevel} />
  <ul>
    <li>Clear ring no longer reappears after release.</li>
    <li>Drawings recover when the app resumes.</li>
  </ul>
{/if}
