<script module lang="ts">
  export const RELEASE_NOTE_SECTION_COUNT = 3;
</script>

<script lang="ts">
  import ReleaseSectionHeading from '../ReleaseSectionHeading.svelte';

  let { visibleSections = RELEASE_NOTE_SECTION_COUNT }: { visibleSections?: number } = $props();
</script>

<!-- Generated by tools/release/gen-release-notes.mjs from releases/1.5.0.md. -->
{#if visibleSections >= 1}
  <ReleaseSectionHeading title="New" level={2} />
  <ul>
    <li>Create 10 free AI pictures—no key needed.</li>
    <li>A new page chip shows and clears the current coloring page.</li>
    <li>Parents choose checks, kids&#39; tools, and report AI pictures.</li>
  </ul>
{/if}
{#if visibleSections >= 2}
  <ReleaseSectionHeading title="Improved" level={2} />
  <ul>
    <li>Smaller first download; coloring art arrives in the background.</li>
    <li>Faster Settings navigation on every screen.</li>
    <li>Smoother iPad drawing, coloring, undo, and saving.</li>
  </ul>
{/if}
{#if visibleSections >= 3}
  <ReleaseSectionHeading title="Fixed" level={2} />
  <ul>
    <li>Settings stays open when choosing a feedback type.</li>
    <li>Magic brush and picture saves recover from rare canvas failures.</li>
  </ul>
{/if}
