import { flushSync, mount, unmount } from 'svelte';
import { afterEach, describe, expect, it } from 'vitest';
import { RELEASE_NOTE_SECTION_COUNT } from './CurrentReleaseNotes.svelte';
import WhatsNewSection from './WhatsNewSection.svelte';

let mounted: ReturnType<typeof mount> | null = null;

afterEach(async () => {
  if (mounted) await unmount(mounted);
  mounted = null;
  document.body.replaceChildren();
});

// The section reveals its release sections a frame at a time; onSettled marks
// the last one added.
async function mountSettled() {
  const target = document.createElement('div');
  document.body.append(target);
  await new Promise<void>((resolve) => {
    mounted = mount(WhatsNewSection, { target, props: { onSettled: resolve } });
  });
  flushSync();
  return target;
}

function headingLevel(heading: Element) {
  return Number(heading.tagName.slice(1));
}

// The date heading is authored here and the section headings are generated by
// tools/release/gen-release-notes.mjs, so only a render sees both levels.
describe("What's New heading outline", () => {
  it('sets every release-section heading exactly one level below the release date', async () => {
    const target = await mountSettled();
    const date = target.querySelector('.whats-new-heading');
    if (!date) throw new Error("What's New rendered no release date heading");
    const sections = [...target.querySelectorAll('.release-section-heading')];

    expect(sections).toHaveLength(RELEASE_NOTE_SECTION_COUNT);
    expect(sections.map(headingLevel)).toEqual(sections.map(() => headingLevel(date) + 1));
  });
});
