import { describe, expect, it } from 'vitest';
import {
  ALLOWED_REFERENCES,
  createIndex,
  extractReferences,
  findUnresolved,
  isScannedDoc,
  pathCandidate,
  report,
  scan,
  staleAllowances,
} from '../check-doc-references.mjs';

const FILES = [
  'package.json',
  'docs/TESTING.md',
  'tools/perf/README.md',
  'tools/perf/ios/capture-webkit-frames.mjs',
  'tools/asset-gen/package.json',
  'tools/asset-gen/README.md',
  'web/src/lib/drawing/engine.ts',
  'web/static/coloring/creatures/owl-tall.light.webp',
];
const PACKAGES = new Map([
  ['', new Set(['check', 'test:tools'])],
  ['tools/asset-gen', new Set(['coloring-fills'])],
]);

const index = (overrides = {}) => createIndex({ files: FILES, packages: PACKAGES, ...overrides });

function unresolved(file, text, overrides) {
  return findUnresolved({ docs: [file], read: () => text, index: index(overrides) }).map(
    ({ kind, ref }) => `${kind} ${ref}`
  );
}

describe('which docs are scanned', () => {
  it.each([
    'docs/TESTING.md',
    '.ruler/skills/build/SKILL.md',
    '.claude/rules/testing.md',
    '.claude/skills/burn-down-audits/SKILL.md',
    '.agents/skills/run-rival-agent/SKILL.md',
  ])('scans %s', (file) => {
    expect(isScannedDoc(file)).toBe(true);
  });

  it.each([
    ['a numbered ADR', 'docs/adrs/0001-one-codebase.md'],
    ['a scratchpad note', 'docs/scratchpad/run.md'],
    ['the audit staging file', 'docs/AUDIT.md'],
    ['a skill note, which narrates retired designs', '.ruler/skill-notes/build.md.template'],
    ['a capability design log', 'tools/rival-agent/NOTES.md'],
    ['a generated skill copy', '.claude/skills/build/SKILL.md'],
    ['a generated Codex skill copy', '.agents/skills/build/SKILL.md'],
    ['a non-Markdown file', 'tools/perf/README.txt'],
  ])('skips %s', (_label, file) => {
    expect(isScannedDoc(file)).toBe(false);
  });

  it('skips a Ruler-generated orientation file by its marker', () => {
    expect(isScannedDoc('tools/CLAUDE.md', '<!-- Source: .ruler/AGENTS.md -->')).toBe(false);
    expect(isScannedDoc('AGENTS.md', '<!-- Generated by Ruler -->')).toBe(false);
  });
});

describe('what reads as a repo path', () => {
  const names = index();

  it.each([
    'docs/TESTING.md',
    'web/src/lib/drawing/engine.ts',
    'src/lib/drawing/engine.ts',
    '../ios/capture.mjs',
    'drawing/engine.ts',
  ])('reads %s as a path', (span) => {
    expect(pathCandidate(span, names)).toBe(span);
  });

  it('strips a line suffix and a trailing slash', () => {
    expect(pathCandidate('web/src/lib/drawing/engine.ts:12-30', names)).toBe(
      'web/src/lib/drawing/engine.ts'
    );
    expect(pathCandidate('tools/perf/', names)).toBe('tools/perf');
  });

  it.each([
    ['a single filename', 'findings.json'],
    ['a route', '/api/generate-image'],
    ['a glob', 'tools/**/*.mjs'],
    ['a template', 'docs/adrs/<NNNN>-title.md'],
    ['a numbered placeholder', 'docs/adrs/NNNN-kebab-case-title.md'],
    ['a dated placeholder', 'docs/review-YYYY-MM-DD.md'],
    ['a counted placeholder', 'web/static/sounds/pencil-N.mp3'],
    ['a URL', 'https://example.com/a/b'],
    ['a GitHub action', 'actions/checkout'],
    ['a coloring page id', 'creatures/owl-tall'],
    ['a path on another machine', 'Library/Preferences/app.plist'],
    ['pure navigation', '../../..'],
    ['a command', 'npm run check'],
  ])('ignores %s', (_label, span) => {
    expect(pathCandidate(span, names)).toBeNull();
  });
});

describe('resolution', () => {
  it('resolves against the doc folder, its ancestors, and the repo root', () => {
    expect(unresolved('tools/perf/README.md', '`ios/capture-webkit-frames.mjs`')).toEqual([]);
    expect(unresolved('tools/perf/README.md', '`docs/TESTING.md`')).toEqual([]);
    expect(unresolved('tools/perf/README.md', '`../perf/ios`')).toEqual([]);
  });

  it('resolves an unambiguous path tail named without its prefix', () => {
    expect(unresolved('docs/TESTING.md', '`lib/drawing/engine.ts`')).toEqual([]);
  });

  it('reports a path that resolves nowhere', () => {
    expect(unresolved('tools/perf/README.md', 'see `../../ios/capture-webkit-frames.mjs`')).toEqual(
      ['path ../../ios/capture-webkit-frames.mjs']
    );
  });

  it('reads relative Markdown links as paths', () => {
    expect(unresolved('docs/TESTING.md', '[perf](../tools/perf/README.md)')).toEqual([]);
    expect(unresolved('docs/TESTING.md', '[gone](../tools/perf/GONE.md)')).toEqual([
      'link ../tools/perf/GONE.md',
    ]);
    expect(unresolved('docs/TESTING.md', '[site](https://splotch.art/a/b.md)')).toEqual([]);
  });

  it('checks a single-file link beside the doc', () => {
    expect(unresolved('tools/perf/README.md', '[docs](../../docs/TESTING.md)')).toEqual([]);
    expect(unresolved('tools/perf/ios/NOTES2.md', '[up](../README.md)')).toEqual([]);
    expect(unresolved('tools/perf/ios/x.md', '[local](README.md)')).toEqual(['link README.md']);
  });

  // A link is followed from where the doc sits; retrying it against each
  // ancestor would pass a link that is broken for every reader.
  it('resolves a link only from the doc folder', () => {
    expect(unresolved('tools/perf/ios/x.md', '[readme](./README.md)')).toEqual([
      'link ./README.md',
    ]);
  });

  it('follows a Ruler orientation source link from its generated location', () => {
    expect(unresolved('tools/.ruler/AGENTS.md', '[perf](perf/README.md)')).toEqual([]);
    expect(unresolved('.ruler/conventions.md', '[testing](docs/TESTING.md)')).toEqual([]);
  });

  it('ignores link syntax quoted in a code span', () => {
    expect(unresolved('docs/TESTING.md', 'write `[x](gone.md)` for a link')).toEqual([]);
  });

  it('refuses a path tail two tracked paths share', () => {
    const files = [...FILES, 'tools/perf/docs/pipeline.md', 'tools/asset-gen/docs/pipeline.md'];
    const shared = createIndex({ files, packages: PACKAGES });
    const findings = findUnresolved({
      docs: ['docs/TESTING.md'],
      read: () => '`docs/pipeline.md`',
      index: shared,
    });
    expect(findings.map(({ ref }) => ref)).toEqual(['docs/pipeline.md']);
  });

  it('leaves a gitignored path alone', () => {
    const ignoredPaths = new Set(['web/build']);
    expect(unresolved('docs/TESTING.md', '`web/build`', { ignoredPaths })).toEqual([]);
  });

  it('never reads a reference inside a fenced block as a path', () => {
    expect(unresolved('docs/TESTING.md', '```sh\ncat web/gone.ts\n```\n')).toEqual([]);
  });

  it('reports the source line even below a fenced block', () => {
    const [finding] = findUnresolved({
      docs: ['docs/TESTING.md'],
      read: () => 'a\n```\nb\n```\nsee `web/gone.ts`\n',
      index: index(),
    });
    expect(finding).toMatchObject({ line: 5, ref: 'web/gone.ts' });
  });
});

describe('npm scripts', () => {
  it('resolves a root script from anywhere, including fenced blocks', () => {
    expect(unresolved('docs/TESTING.md', '```sh\nnpm run test:tools -- --watch\n```')).toEqual([]);
  });

  it('reports a script no package declares', () => {
    expect(unresolved('docs/TESTING.md', 'run `npm run test:gone`')).toEqual(['script test:gone']);
  });

  it('resolves a package alias only inside that package', () => {
    expect(unresolved('tools/asset-gen/README.md', 'npm run coloring-fills')).toEqual([]);
    expect(unresolved('docs/TESTING.md', 'npm run coloring-fills')).toEqual([
      'script coloring-fills',
    ]);
  });

  it('skips npm flags and namespace globs', () => {
    expect(unresolved('docs/TESTING.md', 'npm run --silent check; npm run perf:*')).toEqual([]);
  });
});

describe('identifiers', () => {
  it('are only extracted on request', () => {
    const text = 'call `createEngine()` and read `MAX_TILES`';
    expect(extractReferences(text, index())).toEqual([]);
    expect(
      extractReferences(text, { ...index(), identifiers: true }).map(({ ref }) => ref)
    ).toEqual(['createEngine', 'MAX_TILES']);
  });

  it('resolve against words in tracked source', () => {
    const findings = findUnresolved({
      docs: ['docs/TESTING.md'],
      read: () => '`createEngine()` and `oldHelper()`',
      index: index({ sourceWords: new Set(['createEngine']) }),
      identifiers: true,
    });
    expect(findings.map(({ ref }) => ref)).toEqual(['oldHelper']);
  });

  it('never fail the report', () => {
    const log = { log: () => {}, error: () => {} };
    const findings = [{ file: 'docs/TESTING.md', line: 1, kind: 'identifier', ref: 'oldHelper' }];
    expect(report({ findings, stale: [] }, log)).toBe(0);
  });
});

describe('the allowlist', () => {
  it('gives every entry a reason', () => {
    for (const entry of ALLOWED_REFERENCES) expect(entry.why).toMatch(/\w/);
  });

  it('flags an entry whose reference no longer appears', () => {
    const [entry] = ALLOWED_REFERENCES;
    const stale = staleAllowances({ docs: [entry.doc], read: () => 'rewritten', index: index() });
    expect(stale).toContainEqual(entry);
  });
});

// The gate: every living doc's repo paths and npm scripts resolve, and every
// allowlist entry still matches the reference it exempts.
describe('the repository', () => {
  it('has no unresolved doc references', () => {
    const { findings, stale } = scan();
    expect(findings).toEqual([]);
    expect(stale).toEqual([]);
  });
});
