/**
 * The capture artifact.
 *
 * One envelope for every capture, whatever the transport. The probe records, Node computes:
 * `report` holds the raw tables and is the only part a re-score reads; `summaries` and `verdicts`
 * are derived by the package version in `provenance` and may be regenerated by a later one. An
 * artifact is stored whole; trimming `events` leaves the headline number plausible while the
 * fidelity verdict silently flips to false.
 *
 * Evidence and summaries are typed per scenario kind, so the acceptance rules the package ships and
 * the ones an app adds read the same fields through the same types.
 */

import type { Activation } from './app.js';
import type { FrameStampEpoch } from './probe.js';
import type { ResolvedActionPlan, ScenarioKind } from './scenario.js';
import type { Platform, Shell } from './target.js';
import type {
  ActionSample,
  ActionSummary,
  FramesSummary,
  RepeatedActionSummary,
} from './scoring.js';
import type {
  InputTransportId,
  MeasurementChannelId,
  InstrumentId,
  PageGeometry,
} from './transport.js';

/** Everything that crosses the seam and can change independently, with the policy each follows. */
export declare const COMPAT: {
  /** Major bump: `readArtifact` upgrades or refuses; it never guesses. */
  readonly artifactSchema: 1;
  readonly framesProbeSchema: 2;
  readonly actionsProbeSchema: 2;
  readonly frameStampEpoch: FrameStampEpoch;
  /** Bumps whenever any `summarise*` or `evaluate*` output can change on identical rows; an app regenerates its golden ledgers in the same change that adopts it. */
  readonly scoringEpoch: number;
  /** Package-owned; the app name travels as a separate header. */
  readonly probeHostProtocol: `perf-rig/${number}`;
};

/**
 * Guards run before measurement. A failed guard outside the request's `tolerate` list stops the
 * capture with exit 2, and the artifact is written with the ledger so the failure is evidence.
 */
export type GuardId =
  | 'refused-build-variant'
  | 'build-seams-present'
  | 'served-build-identity'
  | 'page-identity-nonce'
  | 'route-hydrated'
  | 'page-prepared'
  | 'window-fills-screen'
  | 'tab-responsive'
  | 'foreground-package'
  | 'runtime-user-agent'
  | 'packaged-origin'
  | 'entry-module-match'
  | 'service-worker-blocked'
  | 'dimension-observed'
  | 'committed-tool'
  | 'menus-dismissed'
  | 'hit-test-surface'
  | 'prime-verified';

/** Verdicts computed after measurement. A failure exits 1 after the artifact is written. */
export type VerdictId =
  | 'input-received'
  | 'input-fidelity'
  | 'refresh-regime'
  | 'painted-output'
  | 'gesture-plan'
  | 'gesture-repeats'
  | 'prime-between-passes'
  | 'repeated-action-proof'
  | 'capture-runtime'
  | 'host-quiet'
  | 'instrument-restored';

/**
 * `verified`: ran and held. `failed`: ran and did not. `unrecorded`: should have run on this
 * transport and did not; a reader treats it as failed. `not-applicable`: does not apply to this
 * transport, by the package's table, never by omission.
 */
export interface TrustEntry {
  readonly name: GuardId | VerdictId;
  readonly state: 'verified' | 'failed' | 'unrecorded' | 'not-applicable';
  readonly detail?: string;
}

export interface Provenance {
  readonly productCommit: string | null;
  readonly buildEntry: string | null;
  readonly buildDigest: string | null;
  readonly dirty: boolean | null;
  /** Tree hash of the package at the nested rung; a semver once published. */
  readonly harnessVersion: string;
  readonly scoringEpoch: number;
  readonly instrumentFingerprint: string;
  readonly capturedAt: string;
  readonly nonce: string | null;
  readonly pageIdentity:
    'proved-by-url' | 'proved-by-attached-target' | 'proved-by-container-nonce' | 'unprovable';
  readonly pageDelivery: 'browser' | 'remote-preview' | 'packaged';
}

export interface FramesEvidence {
  readonly gesturePlan:
    | { readonly id: string; readonly repeats: number; readonly strokesPerRepeat: number }
    | { readonly id: 'probe-synthetic' | 'human' };
  readonly prime?: {
    readonly verified: boolean;
    readonly repairedAfterSettle: boolean;
    readonly betweenPasses: readonly {
      readonly afterStroke: number;
      readonly ok: boolean;
      readonly detail?: string;
    }[];
  };
  readonly paintedOutput:
    { readonly changed: boolean; readonly surfaces: number } | { readonly error: string };
  readonly repeatedAction?: {
    readonly control: string;
    readonly count: number;
    readonly depthBefore: number;
    readonly depthAfter: number;
    readonly changedEveryStep: boolean;
    readonly samples: readonly {
      readonly index: number;
      readonly engineMs: number;
      readonly nextFrameMs: number;
    }[];
  };
  readonly hostQuiet?: {
    readonly load1Start: number;
    readonly load1End: number;
    readonly cores: number;
    readonly thresholdPerCore: number;
  };
}

export interface ActionsEvidence {
  readonly plan: ResolvedActionPlan;
  readonly frameStampEpoch: FrameStampEpoch;
  readonly activation: Activation;
  /** Allowances the capture was scored under; the fold re-scores under current policy and refuses a superset. */
  readonly gateAllowances: Readonly<
    Record<string, { readonly p95Ms?: number; readonly maxMs?: number }>
  >;
  readonly refreshRatePin?: {
    readonly requestedHz: number;
    readonly verified: boolean;
    readonly restored: boolean;
  };
  readonly deviceUptimeSeconds?: number;
  readonly scrollDelivery?: 'native-gesture' | 'wheel';
}

export interface SessionEvidence {
  readonly beats: readonly {
    readonly label: string;
    readonly startedAtMs: number;
    readonly durationMs: number;
  }[];
}

export interface FirstShowEvidence {
  readonly shells: readonly {
    readonly name: string;
    readonly firstShowMs: readonly number[];
    readonly reopenMs: readonly number[];
  }[];
}

export type EvidenceFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesEvidence
  : K extends 'actions'
    ? ActionsEvidence
    : K extends 'session'
      ? SessionEvidence
      : FirstShowEvidence;

export type SummariesFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesSummary & { readonly repeatedAction?: RepeatedActionSummary }
  : K extends 'actions'
    ? readonly ActionSummary[]
    : undefined;

export type ReportFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesReport
  : K extends 'actions'
    ? ActionsReport
    : TraceReport;

export interface CaptureArtifact<K extends ScenarioKind = ScenarioKind> {
  readonly schema: { readonly name: 'perf-rig.capture'; readonly version: 1 };
  readonly label: string;
  readonly target: string;
  readonly scenario: { readonly kind: K; readonly id: string };
  readonly platform: Platform;
  readonly shell: Shell;
  readonly transport: InputTransportId;
  readonly channel: MeasurementChannelId;
  readonly captureRuntime: string;
  readonly appUrl: string;
  readonly nativePackage?: string;
  readonly provenance: Provenance;
  readonly device: {
    readonly model?: string;
    readonly os?: string;
    readonly identifier: '[redacted]' | null;
  };
  readonly geometry: PageGeometry;
  /** Observed values of every app dimension after setup. */
  readonly dimensions: Readonly<Record<string, string>>;
  readonly instruments: readonly {
    readonly id: InstrumentId;
    readonly files: readonly string[];
    readonly summary?: unknown;
  }[];
  readonly trust: readonly TrustEntry[];
  readonly report: ReportFor<K>;
  readonly evidence: EvidenceFor<K>;
  readonly summaries?: SummariesFor<K>;
  readonly verdicts?: Readonly<Record<string, Verdict>>;
}

export interface FramesReport {
  readonly meta: {
    readonly schema: 2;
    readonly url: string;
    readonly ua: string;
    readonly dpr: number;
    readonly timeOriginUnixMs: number;
    readonly viewport: { readonly width: number; readonly height: number };
    readonly canvasCss: { readonly width: number; readonly height: number };
    readonly canvasBacking: { readonly width: number; readonly height: number };
    readonly measureNames: readonly string[];
    readonly counts: Readonly<Record<string, number>>;
    readonly tool?: string;
  };
  readonly frames: readonly (readonly number[])[];
  readonly events: readonly (readonly number[])[];
  readonly measures: readonly (readonly number[])[];
  readonly history: readonly (readonly number[])[];
  readonly liftLatencies: readonly (readonly number[])[];
  readonly phases: readonly {
    readonly key: string;
    readonly paper: 'blank' | 'page';
    readonly startedAt: number;
    readonly endedAt: number;
    readonly contactMs: number;
    readonly frames: number;
    readonly abandoned?: boolean;
    readonly [passthrough: string]: unknown;
  }[];
  readonly paintedOutput:
    { readonly changed: boolean; readonly surfaces: number } | { readonly error: string };
}

export interface ActionsReport {
  readonly samples: readonly ActionSample[];
}

export interface TraceReport {
  readonly traceFile?: string;
  readonly measures: readonly {
    readonly name: string;
    readonly startTime: number;
    readonly duration: number;
  }[];
  readonly longTasks: readonly { readonly startTime: number; readonly duration: number }[];
}

export interface Verdict {
  readonly passed: boolean;
  readonly reasons: readonly string[];
}

/** Which shell an artifact proves it measured, from transport, packaged origin and package; contradictory fields match neither. */
export declare function runtimeOf(artifact: CaptureArtifact): Shell | 'contradictory';

export declare function artifactDirectory(root: string, label: string, now?: Date): string;
/** Refuses an unknown schema; an app upgrades its pre-package corpus with its own reader. */
export declare function readArtifact(path: string): Promise<CaptureArtifact>;
export declare function isCaptureArtifact(value: unknown): value is CaptureArtifact;
export declare function writeArtifact(path: string, artifact: CaptureArtifact): Promise<void>;
