/**
 * The capture artifact.
 *
 * One envelope for every capture, whatever the transport. The probe records, Node computes:
 * `report` holds the raw tables and is the only part a re-score reads; `summaries` and `verdicts`
 * are derived by the package version in `provenance` and may be regenerated by a later one. An
 * artifact is stored whole; trimming `events` leaves the headline number plausible while the
 * fidelity verdict silently flips to false.
 *
 * The artifact is a discriminated union on `scenario.kind`, so narrowing the kind narrows the
 * report, evidence and summaries with it, and a rule written for one kind is a no-op for the rest.
 */

import type { Activation } from './app.js';
import type { ACTIONS_PROBE_SCHEMA, FrameStampEpoch } from './probe.js';
import type { ResolvedActionPlan, ScenarioKind } from './scenario.js';
import type { Platform, Shell } from './target.js';
import type {
  ActionSample,
  ActionSummary,
  FramesSummary,
  RepeatedActionSummary,
} from './scoring.js';
import type {
  InputTransportId,
  MeasurementChannelId,
  InstrumentId,
  PageGeometry,
  PrimeEntry,
} from './transport.js';

/** Everything that crosses the seam and can change independently, with the policy each follows. */
export declare const COMPAT: {
  /** Major bump: `readArtifact` upgrades or refuses; it never guesses. */
  readonly artifactSchema: 1;
  readonly framesProbeSchema: 2;
  readonly actionsProbeSchema: 2;
  readonly frameStampEpoch: typeof ACTIONS_PROBE_SCHEMA.frameStampEpoch;
  /**
   * Bumps whenever any `summarise*` or `evaluate*` output can change on identical rows. A golden
   * ledger records the epoch it was generated under and its test refuses to compare across a
   * mismatch, so a scorer change without a bump, or a bump without a regeneration, fails by name.
   */
  readonly scoringEpoch: number;
  /** Package-owned; the app name travels as a separate header. */
  readonly probeHostProtocol: `perf-rig/${number}`;
};

/** Guards run before measurement. A failed guard outside `tolerate` stops the capture with exit 2. */
export type GuardId =
  | 'refused-build-variant'
  | 'build-seams-present'
  | 'served-build-identity'
  | 'page-identity-nonce'
  | 'route-hydrated'
  | 'page-prepared'
  | 'window-fills-screen'
  | 'tab-responsive'
  | 'foreground-package'
  | 'runtime-user-agent'
  | 'packaged-origin'
  | 'entry-module-match'
  | 'service-worker-blocked'
  | 'dimension-observed'
  | 'committed-tool'
  | 'menus-dismissed'
  | 'hit-test-surface'
  | 'prime-verified';

/** Verdicts computed after measurement. A failure exits 1 after the artifact is written. */
export type VerdictId =
  | 'input-received'
  | 'input-fidelity'
  | 'refresh-regime'
  | 'painted-output'
  | 'gesture-plan'
  | 'gesture-repeats'
  | 'prime-between-passes'
  | 'repeated-action-proof'
  | 'capture-shell'
  | 'host-quiet'
  | 'instrument-restored';

/**
 * `verified`: ran and held. `failed`: ran and did not. `unrecorded`: should have run on this
 * transport and did not; a reader treats it as failed. `not-applicable`: does not apply to this
 * transport, by the package's table, never by omission. `tolerated`: failed, and the request named
 * it as an accepted exception.
 */
export interface TrustEntry {
  readonly name: GuardId | VerdictId;
  readonly state: 'verified' | 'failed' | 'tolerated' | 'unrecorded' | 'not-applicable';
  readonly evaluatedBy: 'host' | 'page';
  readonly detail?: string;
}

export interface Provenance {
  readonly productCommit: string | null;
  readonly buildEntry: string | null;
  readonly buildDigest: string | null;
  readonly dirty: boolean | null;
  /** Tree hash of the package at the nested rung; a semver once published. */
  readonly harnessVersion: string;
  readonly scoringEpoch: number;
  readonly instrumentFingerprint: string;
  readonly capturedAt: string;
  readonly nonce: string | null;
  readonly pageIdentity:
    'proven-by-url' | 'proven-by-attached-target' | 'proven-by-container-nonce' | 'unprovable';
  readonly pageDelivery: 'browser' | 'remote-preview' | 'packaged';
  /** The gate policy the capture-time verdicts were scored under; a fold re-evaluates under the current one. */
  readonly gatePolicyDigest: string | null;
}

export interface FramesEvidence {
  readonly gesturePlan:
    | { readonly id: string; readonly repeats: number; readonly strokesPerRepeat: number }
    | { readonly id: 'probe-synthetic' | 'human' };
  readonly prime?: {
    readonly verified: boolean;
    readonly repairedAfterSettle: boolean;
    readonly betweenPasses: readonly PrimeEntry[];
  };
  readonly paintedOutput:
    { readonly changed: boolean; readonly surfaces: number } | { readonly error: string };
  readonly repeatedAction?: {
    readonly control: string;
    readonly count: number;
    readonly depthBefore: number;
    readonly depthAfter: number;
    readonly changedEveryStep: boolean;
    readonly samples: readonly {
      readonly index: number;
      readonly engineMs: number;
      readonly nextFrameMs: number;
      readonly startedAt: number;
      readonly endedAt: number;
    }[];
  };
  readonly hostQuiet?: {
    readonly samples: readonly number[];
    readonly cores: number;
    readonly thresholdPerCore: number;
    readonly load1Start: number;
    readonly load1End: number;
  };
}

export interface ActionsEvidence {
  readonly plan: ResolvedActionPlan;
  readonly frameStampEpoch: FrameStampEpoch;
  readonly activation: Activation;
  /** Keyed by action id. The fold re-scores under current policy and refuses a superset. */
  readonly gateAllowances: Readonly<
    Record<string, { readonly p95Ms?: number; readonly maxMs?: number }>
  >;
  readonly refreshRatePin?: {
    readonly requestedHz: number;
    readonly verified: boolean;
    readonly restored: boolean;
  };
  readonly deviceUptimeSeconds?: number;
  readonly scrollDelivery?: 'native-gesture' | 'wheel';
}

export interface SessionEvidence {
  readonly beats: readonly {
    readonly label: string;
    readonly startedAtMs: number;
    readonly durationMs: number;
  }[];
}

export interface FirstShowEvidence {
  readonly shells: readonly {
    readonly name: string;
    readonly firstShowMs: readonly number[];
    readonly reopenMs: readonly number[];
  }[];
}

export type EvidenceFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesEvidence
  : K extends 'actions'
    ? ActionsEvidence
    : K extends 'session'
      ? SessionEvidence
      : FirstShowEvidence;

export type SummariesFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesSummary & { readonly repeatedAction?: RepeatedActionSummary }
  : K extends 'actions'
    ? readonly ActionSummary[]
    : undefined;

export type ReportFor<K extends ScenarioKind> = K extends 'frames'
  ? FramesReport
  : K extends 'actions'
    ? ActionsReport
    : TraceReport;

export interface CaptureArtifactOf<K extends ScenarioKind> {
  readonly schema: {
    readonly name: 'perf-rig.capture';
    readonly version: typeof COMPAT.artifactSchema;
  };
  /** Top-level discriminant, duplicated from `scenario.kind` so narrowing works on the artifact itself. */
  readonly kind: K;
  readonly label: string;
  readonly target: string;
  readonly scenario: { readonly kind: K; readonly id: string };
  readonly platform: Platform;
  readonly shell: Shell;
  readonly transport: InputTransportId;
  readonly channel: MeasurementChannelId;
  readonly captureRuntime: string;
  readonly appUrl: string;
  readonly nativePackage?: string;
  readonly provenance: Provenance;
  readonly device: {
    readonly model?: string;
    readonly os?: string;
    readonly identifier: '[redacted]' | null;
  };
  readonly geometry: PageGeometry;
  /** Observed values of every app dimension after setup. */
  readonly dimensions: Readonly<Record<string, string>>;
  readonly instruments: readonly {
    readonly id: InstrumentId;
    readonly files: readonly string[];
    readonly summary?: unknown;
  }[];
  readonly trust: readonly TrustEntry[];
  readonly report: ReportFor<K>;
  readonly evidence: EvidenceFor<K>;
  readonly summaries?: SummariesFor<K>;
  readonly verdicts?: Readonly<Record<string, Verdict>>;
}

export type CaptureArtifact = { [K in ScenarioKind]: CaptureArtifactOf<K> }[ScenarioKind];

/** Schema 2, keyed as the shipped probe writes it; a renamed key is schema 3 with an upgrade, never a silent change. */
export interface FramesReport {
  readonly meta: {
    readonly schema: 2;
    readonly url: string;
    readonly ua: string;
    readonly dpr: number;
    readonly timeOriginUnixMs: number;
    readonly viewport: { readonly w: number; readonly h: number };
    readonly canvasCss: { readonly w: number; readonly h: number };
    readonly canvasBacking: { readonly w: number; readonly h: number };
    readonly contactTargetMs: number;
    readonly freeDrawMs: number;
    readonly hud: boolean;
    readonly drive: 'mixed' | 'long' | 'short' | null;
    readonly driveHz: number;
    readonly drivePointerType: 'touch' | 'pen' | 'mouse' | null;
    /** The tool label under the key the schema-2 probe writes. */
    readonly brush: string | null;
    readonly historySeam: boolean;
    readonly measureNames: readonly string[];
    readonly counts: Readonly<Record<string, number>>;
    /** App-declared state the rendered probe records beside its own (`theme`, `lineartBlend`). */
    readonly [passthrough: string]: unknown;
  };
  readonly frames: readonly (readonly number[])[];
  readonly events: readonly (readonly number[])[];
  readonly measures: readonly (readonly number[])[];
  readonly history: readonly (readonly number[])[];
  readonly liftLatencies: readonly (readonly number[])[];
  readonly phases: readonly {
    readonly key: string;
    readonly paper: 'blank' | 'page';
    readonly startedAt: number;
    readonly endedAt: number;
    readonly contactMs: number;
    readonly frames: number;
    readonly abandoned?: boolean;
    readonly [passthrough: string]: unknown;
  }[];
  readonly paintedOutput:
    { readonly changed: boolean; readonly surfaces: number } | { readonly error: string };
}

export interface ActionsReport {
  readonly samples: readonly ActionSample[];
}

export interface TraceReport {
  readonly traceFile?: string;
  readonly measures: readonly {
    readonly name: string;
    readonly startTime: number;
    readonly duration: number;
  }[];
  readonly longTasks: readonly { readonly startTime: number; readonly duration: number }[];
}

export interface Verdict {
  readonly passed: boolean;
  readonly reasons: readonly string[];
}

/**
 * Which shell an artifact proves it measured, from transport, packaged origin and package against
 * the app's native contract. Contradictory fields are named so acceptance can quote them.
 */
export declare function shellOf(
  artifact: CaptureArtifact,
  native:
    | {
        readonly android?: { readonly package: string; readonly packagedOrigin: string };
        readonly ios?: { readonly packagedOrigin: string };
      }
    | undefined
): { readonly shell: Shell } | { readonly contradictory: readonly string[] };

export declare function artifactDirectory(root: string, label: string, now?: Date): string;
/** Refuses an unknown schema; an app upgrades its pre-package corpus with its own reader. */
export declare function readArtifact(path: string): Promise<CaptureArtifact>;
export declare function isCaptureArtifact(value: unknown): value is CaptureArtifact;
export declare function writeArtifact(path: string, artifact: CaptureArtifact): Promise<void>;
