import { describe, expect, it } from 'vitest';
import {
  parseReleaseSource,
  renderReleaseComponent,
  validateStoreText,
} from '../generate-releases.mjs';

describe('parseReleaseSource', () => {
  it('formats a validated release date for the generated app data', () => {
    expect(
      parseReleaseSource(
        '2.0.0.md',
        '---\nversion: 2.0.0\ndate: 2026-07-28\n---\n\n## New\n\nFaster drawing.'
      ).dateLabel
    ).toBe('July 28, 2026');
  });

  it.each(['07/28/2026', '2026-07-28  # ship day', '', '2026-13-01'])(
    'rejects invalid release date frontmatter %j',
    (date) => {
      expect(() =>
        parseReleaseSource(
          '2.0.0.md',
          `---\nversion: 2.0.0\ndate: ${date}\n---\n\n## New\n\nFaster drawing.`
        )
      ).toThrow(/2\.0\.0\.md: date must/);
    }
  );

  it('rejects impossible calendar dates', () => {
    expect(() =>
      parseReleaseSource(
        '2.0.0.md',
        '---\nversion: 2.0.0\ndate: 2026-02-29\n---\n\n## New\n\nFaster drawing.'
      )
    ).toThrow('2.0.0.md: date must be a real calendar date');
  });
});

describe('validateStoreText', () => {
  it('accepts ordinary plain text', () => {
    expect(() => validateStoreText('Faster drawing where 2 < 3 and 5 > 4.')).not.toThrow();
  });

  it('rejects tag-shaped markup', () => {
    expect(() =>
      validateStoreText('App updates no longer leave stale content.\n</content>')
    ).toThrow('Store text contains HTML/XML-like markup');
  });
});

describe('renderReleaseComponent', () => {
  it('emits compile-time markup and escapes Svelte expression braces', () => {
    expect(renderReleaseComponent('## New\n\n* Draw `{fast}`.', '2.0.0.md')).toBe(
      '<script module lang="ts">\n  export const RELEASE_NOTE_SECTION_COUNT = 1;\n</script>\n\n' +
        '<script lang="ts">\n  let { visibleSections = RELEASE_NOTE_SECTION_COUNT }: { visibleSections?: number } = $props();\n</script>\n\n' +
        '<!-- Generated by scripts/generate-releases.mjs from releases/2.0.0.md. -->\n' +
        '{#if visibleSections >= 1}\n' +
        '  <h2>New</h2>\n  <ul>\n    <li>Draw <code>&#123;fast&#125;</code>.</li>\n  </ul>\n' +
        '{/if}\n'
    );
  });

  it('splits level-two release sections into separate presentation chunks', () => {
    const component = renderReleaseComponent('## New\n\nFirst.\n\n## Fixed\n\nSecond.', '2.0.0.md');

    expect(component).toContain('export const RELEASE_NOTE_SECTION_COUNT = 2;');
    expect(component).toContain('{#if visibleSections >= 1}\n  <h2>New</h2>');
    expect(component).toContain('{#if visibleSections >= 2}\n  <h2>Fixed</h2>');
  });
});
