name: Upload Maestro report
description: Upload the Maestro test report

inputs:
  name:
    description: Artifact name
    required: true

runs:
  using: composite
  steps:
    - if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}
        path: ~/.maestro/tests/
        retention-days: 7
        if-no-files-found: ignore
