name: Upload Maestro report
description: Upload the Maestro test report

inputs:
  name:
    description: Artifact name
    required: true

runs:
  using: composite
  steps:
    - if: ${{ !cancelled() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.name }}
        path: ~/.maestro/tests/
        retention-days: 7
        if-no-files-found: ignore
