<script lang="ts">
  import ReleaseSectionHeading from '$lib/components/ReleaseSectionHeading.svelte';
  import SquiggleRule from '$lib/components/design/SquiggleRule.svelte';
  import Icon from '$pageIcon';
</script>

<!-- Generated by tools/release/gen-release-notes.mjs from every releases/*.md file. -->
<div class="release-history">
  <article class="release" id="release-1-6-0" data-hue="Purple">
    <SquiggleRule />
    <header class="release-header">
      <div class="release-title"><h2>Version 1.6.0</h2><span class="release-latest">Latest</span></div>
      <div class="release-date"><time datetime="2026-09-09">September 9, 2026</time><span class="release-ago" data-ago-for="2026-09-09" aria-hidden="true"></span></div>
    </header>
    <div class="release-notes">
      <ReleaseSectionHeading title="New" level={3} />
      <ul role="list">
        <li>Pick sounds for each part of the app — plus a clear sound.</li>
        <li>Dottie the mascot now reacts on error screens.</li>
      </ul>
      <ReleaseSectionHeading title="Improved" level={3} />
      <ul role="list">
        <li>AI pictures are opt-in, with clearer errors and retries.</li>
        <li>Playful motion: menus pop from buttons, undo spins, clearing sweeps to the trash.</li>
        <li>Crisper coloring pages that load faster.</li>
        <li>Smoother drawing on iPad and Android.</li>
        <li>App updates apply without interrupting drawing.</li>
      </ul>
      <ReleaseSectionHeading title="Fixed" level={3} />
      <ul role="list">
        <li>Clear ring no longer reappears after release.</li>
        <li>Drawings recover when the app resumes.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-5-0" data-hue="Blue">
    <SquiggleRule />
    <header class="release-header">
      <div class="release-title"><h2>Version 1.5.0</h2></div>
      <div class="release-date"><time datetime="2026-08-12">August 12, 2026</time><span class="release-ago" data-ago-for="2026-08-12" aria-hidden="true"></span></div>
    </header>
    <div class="release-notes">
      <ReleaseSectionHeading title="New" level={3} />
      <ul role="list">
        <li>Create 10 free AI pictures — no key needed.</li>
        <li>A new page chip shows and clears the current coloring page.</li>
        <li>Parents choose checks, kids&#39; tools, and report AI pictures.</li>
      </ul>
      <ReleaseSectionHeading title="Improved" level={3} />
      <ul role="list">
        <li>Smaller first download; coloring art arrives in the background.</li>
        <li>Faster Settings navigation on every screen.</li>
        <li>Smoother iPad drawing, coloring, undo, and saving.</li>
      </ul>
      <ReleaseSectionHeading title="Fixed" level={3} />
      <ul role="list">
        <li>Settings stays open when choosing a feedback type.</li>
        <li>Magic brush and picture saves recover from rare canvas failures.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-4-0" data-hue="Green">
    <SquiggleRule />
    <header class="release-header">
      <div class="release-title"><h2>Version 1.4.0</h2></div>
      <div class="release-date"><time datetime="2026-07-28">July 28, 2026</time><span class="release-ago" data-ago-for="2026-07-28" aria-hidden="true"></span></div>
    </header>
    <div class="release-notes">
      <ReleaseSectionHeading title="New" level={3} />
      <ul role="list">
        <li>Dark mode — Light, Dark, or follow your device.</li>
        <li>A wax crayon brush, from the new Brush Menu.</li>
        <li>The magic brush now works on any drawing.</li>
        <li>Report a bug from Settings.</li>
      </ul>
      <ReleaseSectionHeading title="Improved" level={3} />
      <ul role="list">
        <li>Rotating your device keeps the paper upright.</li>
        <li>Undo now goes back 20 steps.</li>
        <li>A bigger eraser, sized as holes in the paper.</li>
      </ul>
      <ReleaseSectionHeading title="Fixed" level={3} />
      <ul role="list">
        <li>The magic brush no longer leaves ghost outlines.</li>
        <li>Swatches and pages read correctly in dark mode.</li>
        <li>The drag-to-clear tutorial no longer vanishes instantly.</li>
      </ul>
    </div>
  </article>

  <details class="release-older" data-older-count="5">
    <summary class="release-older-toggle"><span class="older-blob" aria-hidden="true"><Icon name="chevron-left" class="older-icon" /></span>Show 5 older releases</summary>
    <SquiggleRule />
    <article class="release" id="release-1-3-0" data-hue="Orange">
      <SquiggleRule />
      <header class="release-header">
        <div class="release-title"><h2>Version 1.3.0</h2></div>
        <div class="release-date"><time datetime="2026-07-05">July 5, 2026</time><span class="release-ago" data-ago-for="2026-07-05" aria-hidden="true"></span></div>
      </header>
      <div class="release-notes">
        <ReleaseSectionHeading title="New" level={3} />
        <ul role="list">
          <li>Settings: a slider to resize the on-screen buttons.</li>
          <li>Save your drawings straight to a folder on your computer (web).</li>
          <li>A fullscreen button for a distraction-free canvas (web).</li>
          <li>Add Splotch to your home screen with a friendly one-tap install prompt (web).</li>
          <li>Native Apple Pencil support, including a double-tap-to-erase setting.</li>
        </ul>
        <ReleaseSectionHeading title="Improved" level={3} />
        <ul role="list">
          <li>Faster first load and quicker startup.</li>
          <li>Bigger, easier-to-tap buttons and color swatches.</li>
          <li>Sliders now snap to their default value.</li>
        </ul>
        <ReleaseSectionHeading title="Fixed" level={3} />
        <ul role="list">
          <li>Apple Pencil strokes and quick taps no longer get dropped.</li>
          <li>White strokes are now easy to see while drawing.</li>
          <li>The color palette stays centered in landscape.</li>
          <li>Menus no longer overlap on small phones.</li>
          <li>Double-tapping a button no longer opens things twice.</li>
        </ul>
      </div>
    </article>

    <article class="release" id="release-1-2-0" data-hue="Pink">
      <SquiggleRule />
      <header class="release-header">
        <div class="release-title"><h2>Version 1.2.0</h2></div>
        <div class="release-date"><time datetime="2026-06-22">June 22, 2026</time><span class="release-ago" data-ago-for="2026-06-22" aria-hidden="true"></span></div>
      </header>
      <div class="release-notes">
        <ReleaseSectionHeading title="New" level={3} />
        <ul role="list">
          <li>Splotch is now on iPhone and iPad.</li>
          <li>A volume slider to fine-tune the sound.</li>
          <li>Swipe between tabs in Settings.</li>
        </ul>
        <ReleaseSectionHeading title="Improved" level={3} />
        <ul role="list">
          <li>Smoother, crisper strokes.</li>
          <li>Faster drawing and saving.</li>
        </ul>
        <ReleaseSectionHeading title="Fixed" level={3} />
        <ul role="list">
          <li>The first stroke now always draws.</li>
          <li>No more streaky multi-touch lines on iPhone/iPad.</li>
          <li>Saving no longer creates a blank picture.</li>
          <li>App updates no longer leave stale content.</li>
        </ul>
      </div>
    </article>

    <article class="release" id="release-1-1-0" data-hue="Red">
      <SquiggleRule />
      <header class="release-header">
        <div class="release-title"><h2>Version 1.1.0</h2></div>
        <div class="release-date"><time datetime="2026-06-05">June 5, 2026</time><span class="release-ago" data-ago-for="2026-06-05" aria-hidden="true"></span></div>
      </header>
      <div class="release-notes">
        <ReleaseSectionHeading title="New" level={3} />
        <ul role="list">
          <li>Lock screen rotation so your drawing stays put — on by default.</li>
          <li>Tap the speaker icon to mute or unmute sounds.</li>
        </ul>
        <ReleaseSectionHeading title="Improved" level={3} />
        <ul role="list">
          <li>Coloring pages now adapt to both portrait and landscape.</li>
          <li>Sounds start sooner for snappier feedback.</li>
          <li>Better screen-reader support for in-app messages.</li>
        </ul>
        <ReleaseSectionHeading title="Fixed" level={3} />
        <ul role="list">
          <li>Your coloring page no longer resets when you rotate the device.</li>
          <li>Fixed the layout on wide screens.</li>
        </ul>
      </div>
    </article>

    <article class="release" id="release-1-0-1" data-hue="Purple">
      <SquiggleRule />
      <header class="release-header">
        <div class="release-title"><h2>Version 1.0.1</h2></div>
        <div class="release-date"><time datetime="2026-06-03">June 3, 2026</time><span class="release-ago" data-ago-for="2026-06-03" aria-hidden="true"></span></div>
      </header>
      <div class="release-notes">
        <ReleaseSectionHeading title="Improved" level={3} />
        <ul role="list">
          <li>More colors now fit on smaller screens.</li>
          <li>The clear button is friendlier and more fun.</li>
          <li>A colorful gradient sweeps in while you&#39;re clearing the canvas.</li>
        </ul>
        <ReleaseSectionHeading title="Fixed" level={3} />
        <ul role="list">
          <li>The color palette now adapts more gracefully across devices.</li>
        </ul>
      </div>
    </article>

    <article class="release" id="release-1-0-0" data-hue="Blue">
      <SquiggleRule />
      <header class="release-header">
        <div class="release-title"><h2>Version 1.0.0</h2></div>
        <div class="release-date"><time datetime="2026-06-01">June 1, 2026</time><span class="release-ago" data-ago-for="2026-06-01" aria-hidden="true"></span></div>
      </header>
      <div class="release-notes">
        <ReleaseSectionHeading title="New" level={3} />
        <ul role="list">
          <li>First public release of Splotch — a quiet, ad-free drawing app made for the youngest artists.</li>
          <li>Draw with big, chunky, crayon-like strokes and a row of bright, friendly colors.</li>
          <li>Rainbow color picker for hundreds more colors.</li>
          <li>Coloring book pages to fill in.</li>
          <li>Settings: preferences, install help, and an About page — no ads, no tracking, no accounts.</li>
        </ul>
      </div>
    </article>
  </details>
</div>
