<script lang="ts"></script>

<!-- Generated by tools/release/generate-releases.mjs from every releases/*.md file. -->
<div class="release-history">
  <article class="release" id="release-1-4-0">
    <header class="release-header">
      <h2>Version 1.4.0</h2>
      <time datetime="2026-07-28">July 28, 2026</time>
    </header>
    <div class="release-notes">
      <h3>✨ New</h3>
      <ul>
        <li>Dark mode — Light, Dark, or follow your device.</li>
        <li>A wax crayon brush, from the new Brush Menu.</li>
        <li>The magic brush now works on any drawing.</li>
        <li>Report a bug from Settings.</li>
      </ul>
      <h3>🚀 Improved</h3>
      <ul>
        <li>Rotating your device keeps the paper upright.</li>
        <li>Undo now goes back 20 steps.</li>
        <li>A bigger eraser, sized as holes in the paper.</li>
      </ul>
      <h3>🛠 Fixed</h3>
      <ul>
        <li>The magic brush no longer leaves ghost outlines.</li>
        <li>Swatches and pages read correctly in dark mode.</li>
        <li>The drag-to-clear tutorial no longer vanishes instantly.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-3-0">
    <header class="release-header">
      <h2>Version 1.3.0</h2>
      <time datetime="2026-07-05">July 5, 2026</time>
    </header>
    <div class="release-notes">
      <h3>✨ New</h3>
      <ul>
        <li>Settings: a slider to resize the on-screen buttons.</li>
        <li>Save your drawings straight to a folder on your computer (web).</li>
        <li>A fullscreen button for a distraction-free canvas (web).</li>
        <li>Add Splotch to your home screen with a friendly one-tap install prompt (web).</li>
        <li>Native Apple Pencil support, including a double-tap-to-erase setting.</li>
      </ul>
      <h3>🚀 Improved</h3>
      <ul>
        <li>Faster first load and quicker startup.</li>
        <li>Bigger, easier-to-tap buttons and color swatches.</li>
        <li>Sliders now snap to their default value.</li>
      </ul>
      <h3>🛠 Fixed</h3>
      <ul>
        <li>Apple Pencil strokes and quick taps no longer get dropped.</li>
        <li>White strokes are now easy to see while drawing.</li>
        <li>The color palette stays centered in landscape.</li>
        <li>Menus no longer overlap on small phones.</li>
        <li>Double-tapping a button no longer opens things twice.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-2-0">
    <header class="release-header">
      <h2>Version 1.2.0</h2>
      <time datetime="2026-06-22">June 22, 2026</time>
    </header>
    <div class="release-notes">
      <h3>✨ New</h3>
      <ul>
        <li>Splotch is now on iPhone and iPad.</li>
        <li>A volume slider to fine-tune the sound.</li>
        <li>Swipe between tabs in Settings.</li>
      </ul>
      <h3>🚀 Improved</h3>
      <ul>
        <li>Smoother, crisper strokes.</li>
        <li>Faster drawing and saving.</li>
      </ul>
      <h3>🛠 Fixed</h3>
      <ul>
        <li>The first stroke now always draws.</li>
        <li>No more streaky multi-touch lines on iPhone/iPad.</li>
        <li>Saving no longer creates a blank picture.</li>
        <li>App updates no longer leave stale content.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-1-0">
    <header class="release-header">
      <h2>Version 1.1.0</h2>
      <time datetime="2026-06-05">June 5, 2026</time>
    </header>
    <div class="release-notes">
      <h3>✨ New</h3>
      <ul>
        <li>Lock screen rotation so your drawing stays put — on by default.</li>
        <li>Tap the speaker icon to mute or unmute sounds.</li>
      </ul>
      <h3>🚀 Improved</h3>
      <ul>
        <li>Coloring pages now adapt to both portrait and landscape.</li>
        <li>Sounds start sooner for snappier feedback.</li>
        <li>Better screen-reader support for in-app messages.</li>
      </ul>
      <h3>🛠 Fixed</h3>
      <ul>
        <li>Your coloring page no longer resets when you rotate the device.</li>
        <li>Fixed the layout on wide screens.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-0-1">
    <header class="release-header">
      <h2>Version 1.0.1</h2>
      <time datetime="2026-06-03">June 3, 2026</time>
    </header>
    <div class="release-notes">
      <h3>🚀 Improved</h3>
      <ul>
        <li>More colors now fit on smaller screens.</li>
        <li>The clear button is friendlier and more fun.</li>
        <li>A colorful gradient sweeps in while you&#39;re clearing the canvas.</li>
      </ul>
      <h3>🛠 Fixed</h3>
      <ul>
        <li>The color palette now adapts more gracefully across devices.</li>
      </ul>
    </div>
  </article>

  <article class="release" id="release-1-0-0">
    <header class="release-header">
      <h2>Version 1.0.0</h2>
      <time datetime="2026-06-01">June 1, 2026</time>
    </header>
    <div class="release-notes">
      <h3>✨ New</h3>
      <ul>
        <li>First public release of Splotch — a quiet, ad-free drawing app made for the youngest artists.</li>
        <li>Draw with big, chunky, crayon-like strokes and a row of bright, friendly colors.</li>
        <li>Rainbow color picker for hundreds more colors.</li>
        <li>Coloring book pages to fill in.</li>
        <li>Settings: preferences, install help, and an About page — no ads, no tracking, no accounts.</li>
      </ul>
    </div>
  </article>
</div>
